server {
    #서비스 포트
    listen  80;
    listen  [::]:80;

    #access_log /var/log/nginx/host.access.log main;

    #서비스 파일 위치
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    #프록시 api 위치
    location /api {
        proxy_pass http://restapi:5000;
    }

}